# Generated by Django 5.2.8 on 2025-11-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('health', 'Health'), ('finance', 'Finance'), ('sports', 'Sports'), ('education', 'Education')], default='technology', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
